# name: Deploy Utilify

# on:
#   push:
#     branches:
#       - main

#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v6

#       - name: Setup Node
#         uses: actions/setup-node@v6
#         with:
#           node-version: 20
#           cache: npm

#       - name: Install Dependencies
#         run: npm ci

#       - name: Build App
#         run: npm run build

#       - name: Verify Build Output
#         run: ls -R dist

#       - name: Prepare Deployment Package
#         run: |
#           rm -rf deploy
#           mkdir deploy

#           cp -r dist deploy/
#           cp package.json deploy/
#           cp package-lock.json deploy/ || true

#           cat <<EOF > deploy/.htaccess
#           # cPanel Node.js App Safe Mode
          
#           RewriteEngine On
#           RewriteCond %{REQUEST_FILENAME} !-f
#           RewriteCond %{REQUEST_FILENAME} !-d
#           RewriteRule ^ - [L]
          
#           Header always set X-Content-Type-Options "nosniff"
#           Header always set X-Frame-Options "SAMEORIGIN"
#           EOF

#       - name: Deploy to cPanel
#         uses: easingthemes/ssh-deploy@main
#         with:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
#           REMOTE_HOST: ${{ secrets.HOST }}
#           REMOTE_USER: ${{ secrets.USERNAME }}
#           REMOTE_PORT: ${{ secrets.PORT }}
#           SOURCE: "deploy/"
#           TARGET: /home/${{ secrets.USERNAME }}/utilify/
#           ARGS: "-rlgoDzvc --delete"
